//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTimers.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Timer1Enabled {
            get {
                return ((bool)(this["Timer1Enabled"]));
            }
            set {
                this["Timer1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Timer2Enabled {
            get {
                return ((bool)(this["Timer2Enabled"]));
            }
            set {
                this["Timer2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Timer3Enabled {
            get {
                return ((bool)(this["Timer3Enabled"]));
            }
            set {
                this["Timer3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timer4Enabled {
            get {
                return ((bool)(this["Timer4Enabled"]));
            }
            set {
                this["Timer4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timer5Enabled {
            get {
                return ((bool)(this["Timer5Enabled"]));
            }
            set {
                this["Timer5Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Artillery Shrine")]
        public string Timer1Label {
            get {
                return ((string)(this["Timer1Label"]));
            }
            set {
                this["Timer1Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Channeling Shrine")]
        public string Timer2Label {
            get {
                return ((string)(this["Timer2Label"]));
            }
            set {
                this["Timer2Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Glory Shrine")]
        public string Timer3Label {
            get {
                return ((string)(this["Timer3Label"]));
            }
            set {
                this["Timer3Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer4Label {
            get {
                return ((string)(this["Timer4Label"]));
            }
            set {
                this["Timer4Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer5Label {
            get {
                return ((string)(this["Timer5Label"]));
            }
            set {
                this["Timer5Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57.81")]
        public double Timer1Duration {
            get {
                return ((double)(this["Timer1Duration"]));
            }
            set {
                this["Timer1Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57.81")]
        public double Timer2Duration {
            get {
                return ((double)(this["Timer2Duration"]));
            }
            set {
                this["Timer2Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57.81")]
        public double Timer3Duration {
            get {
                return ((double)(this["Timer3Duration"]));
            }
            set {
                this["Timer3Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Timer4Duration {
            get {
                return ((double)(this["Timer4Duration"]));
            }
            set {
                this["Timer4Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Timer5Duration {
            get {
                return ((double)(this["Timer5Duration"]));
            }
            set {
                this["Timer5Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control")]
        public string Timer1ModifierKey {
            get {
                return ((string)(this["Timer1ModifierKey"]));
            }
            set {
                this["Timer1ModifierKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control")]
        public string Timer2ModifierKey {
            get {
                return ((string)(this["Timer2ModifierKey"]));
            }
            set {
                this["Timer2ModifierKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control")]
        public string Timer3ModifierKey {
            get {
                return ((string)(this["Timer3ModifierKey"]));
            }
            set {
                this["Timer3ModifierKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer4ModifierKey {
            get {
                return ((string)(this["Timer4ModifierKey"]));
            }
            set {
                this["Timer4ModifierKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer5ModifierKey {
            get {
                return ((string)(this["Timer5ModifierKey"]));
            }
            set {
                this["Timer5ModifierKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e")]
        public string Timer1Keybind {
            get {
                return ((string)(this["Timer1Keybind"]));
            }
            set {
                this["Timer1Keybind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("r")]
        public string Timer2Keybind {
            get {
                return ((string)(this["Timer2Keybind"]));
            }
            set {
                this["Timer2Keybind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t")]
        public string Timer3Keybind {
            get {
                return ((string)(this["Timer3Keybind"]));
            }
            set {
                this["Timer3Keybind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer4Keybind {
            get {
                return ((string)(this["Timer4Keybind"]));
            }
            set {
                this["Timer4Keybind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Timer5Keybind {
            get {
                return ((string)(this["Timer5Keybind"]));
            }
            set {
                this["Timer5Keybind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"C:\Users\Jeremy\My Drive\D4\Gauntlet S3W2\S3W2-1.png,C:\Users\Jeremy\My Drive\D4\Gauntlet S3W2\S3W2-2.png,C:\Users\Jeremy\My Drive\D4\Gauntlet S3W2\S3W2-3.png,C:\Users\Jeremy\My Drive\D4\Gauntlet S3W2\S3W2-4.png,C:\Users\Jeremy\My Drive\D4\Gauntlet S3W2\S3W2-5.png
")]
        public string OverlayImages {
            get {
                return ((string)(this["OverlayImages"]));
            }
            set {
                this["OverlayImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public string NextOverlayImageKey {
            get {
                return ((string)(this["NextOverlayImageKey"]));
            }
            set {
                this["NextOverlayImageKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string PreviousOverlayImageKey {
            get {
                return ((string)(this["PreviousOverlayImageKey"]));
            }
            set {
                this["PreviousOverlayImageKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableOverlayImages {
            get {
                return ((bool)(this["EnableOverlayImages"]));
            }
            set {
                this["EnableOverlayImages"] = value;
            }
        }
    }
}
